export const mockProducts = [
  {
    id: 1,
    name: 'Fresh Apples',
    category: 'fruits',
    price: 120,
    originalPrice: 150,
    image: '/images/products/product-1-apples.jpg',
    rating: 4.5,
    reviews: 120,
    description: 'Crispy and sweet apples, perfect for daily consumption.',
    quantity: '1 kg',
    availability: true,
    inStock: 45,
  },
  {
    id: 2,
    name: 'Organic Tomatoes',
    category: 'vegetables',
    price: 45,
    originalPrice: 60,
    image: '/images/products/product-2-tomatoes.jpg',
    rating: 4.2,
    reviews: 89,
    description: 'Fresh organic tomatoes, pesticide-free.',
    quantity: '500g',
    availability: true,
    inStock: 120,
  },
  {
    id: 3,
    name: 'Whole Milk',
    category: 'dairy',
    price: 60,
    originalPrice: 75,
    image: '/images/products/product-3-milk.jpg',
    rating: 4.8,
    reviews: 250,
    description: 'Pure, creamy whole milk from trusted dairy farms.',
    quantity: '1L',
    availability: true,
    inStock: 200,
  },
  {
    id: 4,
    name: 'Basmati Rice',
    category: 'pantry',
    price: 350,
    originalPrice: 400,
    image: '/images/products/product-4-rice.jpg',
    rating: 4.6,
    reviews: 180,
    description: 'Premium long-grain basmati rice, aromatic and fluffy.',
    quantity: '2 kg',
    availability: true,
    inStock: 90,
  },
  {
    id: 5,
    name: 'Fresh Bananas',
    category: 'fruits',
    price: 50,
    originalPrice: 60,
    image: '/images/products/product-5-bananas.jpg',
    rating: 4.4,
    reviews: 156,
    description: 'Golden ripe bananas, rich in potassium.',
    quantity: '1 bunch',
    availability: true,
    inStock: 300,
  },
  {
    id: 6,
    name: 'Spinach (Fresh)',
    category: 'vegetables',
    price: 35,
    originalPrice: 50,
    image: '/images/products/product-6-spinach.jpg',
    rating: 4.3,
    reviews: 72,
    description: 'Nutritious fresh spinach, perfect for salads and cooking.',
    quantity: '250g',
    availability: true,
    inStock: 60,
  },
];

export const mockCategories = [
  { id: 1, name: 'Fruits', key: 'fruits', icon: '🍎', count: 45 },
  { id: 2, name: 'Vegetables', key: 'vegetables', icon: '🥬', count: 62 },
  { id: 3, name: 'Dairy', key: 'dairy', icon: '🥛', count: 28 },
  { id: 4, name: 'Pantry', key: 'pantry', icon: '🥫', count: 156 },
];

export const mockSlots = [
  { id: 1, date: '2024-11-23', time: '8:00 AM - 10:00 AM', available: true, slots: 5 },
  { id: 2, date: '2024-11-23', time: '10:00 AM - 12:00 PM', available: true, slots: 8 },
  { id: 3, date: '2024-11-23', time: '2:00 PM - 4:00 PM', available: false, slots: 0 },
  { id: 4, date: '2024-11-24', time: '8:00 AM - 10:00 AM', available: true, slots: 10 },
];

export const mockSubscriptions = [
  {
    id: 1,
    name: 'Weekly Veggie Box',
    description: 'Fresh vegetables delivered every week',
    price: 299,
    originalPrice: 399,
    frequency: 'weekly',
    items: ['Spinach', 'Tomatoes', 'Carrots', 'Onions'],
    image: '/images/subscriptions/sub-1-veggie-box.jpg',
    savings: '25%',
  },
  {
    id: 2,
    name: 'Family Essentials',
    description: 'Daily essentials for your family',
    price: 499,
    originalPrice: 699,
    frequency: 'weekly',
    items: ['Milk', 'Bread', 'Eggs', 'Butter'],
    image: '/images/subscriptions/sub-2-essentials.jpg',
    savings: '28%',
  },
];

export const mockOrders = [
  {
    id: 'ORD001',
    date: '2024-11-20',
    status: 'delivered',
    items: [
      { productId: 1, name: 'Fresh Apples', quantity: 2, price: 120 },
      { productId: 3, name: 'Whole Milk', quantity: 1, price: 60 },
    ],
    total: 300,
  },
];
